---
title: Jesse Campbell
url: https://jesselcampbell.com
description: Product designer living in Victoria, Canada.
timezone: America/Vancouver

contact:
  email: jesselcampbell@gmail.com
  medium:
    username: jesselcampbell
    url: https://medium.com/@jesselcampbell
  instagram:
    username: jesselcampbell
    url: https://instagram.com/jesselcampbell

collections:
  work:
    title: Work
    output: true
  uploads:
    title: Uploads
    output: true

exclude:
- Gemfile
- Gemfile.lock
