---
title: Jesse Campbell
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
baseurl: ''
url: https://jesselcampbell.com
description: Digital Product Designer
status: Currently making things with Pixel Union.
contact:
  email: jesselcampbell@gmail.com
  medium:
    username: jesselcampbell
    url: https://medium.com/@jesselcampbell
  instagram:
    username: jesselcampbell
    url: https://instagram.com/jesselcampbell
exclude:
- Gemfile
- Gemfile.lock
- readme.md
- package.json
- node_modules
- gulpfile.js
- _assets
gems:
- jekyll-sitemap
