---
title: Jesse Campbell
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl:
url: https://jesselcampbell.com
description: Digital Product Designer
status: Currently making things with Pixel Union.
contact:
  email: jesselcampbell@gmail.com
  medium: jesselcampbell
  instagram: jesselcampbell
  github: jesselcampbell
exclude:
- Gemfile
- Gemfile.lock
- readme.md
- package.json
- node_modules
- gulpfile.js
- _assets
gems:
- jekyll-sitemap
