---
title: Jesse Campbell
timezone: America/Los_Angeles
collections:
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
url: https://jesselcampbell.com
description: Product designer living in Victoria, Canada.
contact:
  email: jesselcampbell@gmail.com
  medium:
    username: jesselcampbell
    url: https://medium.com/@jesselcampbell
  instagram:
    username: jesselcampbell
    url: https://instagram.com/jesselcampbell
exclude:
- Gemfile
- Gemfile.lock
