# Basic Info
title: Jesse Campbell
baseurl: ""
url: "https://jesselcampbell.com"
timezone: America/Los_Angeles
description: Digital Product Designer
status: Currently making things with Pixel Union.
contact:
  email: jesselcampbell@gmail.com
  medium:
    username: jesselcampbell
    url: https://medium.com/@jesselcampbell
  instagram:
    username: jesselcampbell
    url: https://instagram.com/jesselcampbell

# Siteleaf
collections:
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - package.json
  - node_modules
  - gulpfile.js
  - _assets

# Gems
gems:
  - jekyll-sitemap
